try
external_routine
catch
EXTERNAL_FAILURE
Execution completed
