try
catch
EXTERNAL_FAILURE
Execution completed
